### ISSUE TITLE
Unable to build custom add-on insede Home Assistant

### ISSUE THREAD

**Issue by bigmoby** [home-assistant/builder#68]
After a successful build and push in a Docker repository, a custom add-on I developed was't able to build in Home Assistant in an update process. The following error was thrown:

`21-01-30 22:51:25 ERROR (MainThread) [supervisor.jobs] Unhandled exception: You must specify a directory to build in path
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 61, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 280, in update
    await addon.instance.update(store.version, store.image)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/interface.py", line 359, in _update
    self._install(version, image=image, latest=latest)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 401, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 414, in _build
    image, log = self.sys_docker.images.build(
  File "/usr/local/lib/python3.8/site-packages/docker/models/images.py", line 279, in build
    resp = self.client.api.build(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/build.py", line 148, in build
    raise TypeError("You must specify a directory to build in path")
TypeError: You must specify a directory to build in path`

Thank you so much for your help or suggestions.

**Comment by bigmoby** [comment]
I'm so sorry. My fault!
